yarnPath: .yarn/releases/yarn-3.2.1.cjs
packageExtensions:
  'gatsby-theme-i18n@*':
    dependencies:
      mkdirp: '*'
  'gatsby-plugin-react-i18next@*':
    dependencies:
      '@types/reach__router': '*'
  'styled-components@^5':
    dependencies:
      'react-is': '*'
